<Project>
  <Import Project="$(MsBuildThisFileDirectory)eng/Common.targets" />
  <Import Project="$(MsBuildThisFileDirectory)eng/$(ProjectType).targets" Condition="$(ProjectType) != ''" />

  <ItemGroup>
    <Using Include="System.Collections" />
    <Using Include="System.Collections.Concurrent" />
    <Using Include="System.Diagnostics" />
    <Using Include="System.Reflection" />
    <Using Remove="System.Net.Http" />
  </ItemGroup>

  <ItemGroup Condition="'$(IncludeFencesUsings)' == 'true'">
    <Using Include="Paramore.Fences.Bulkhead" />
    <Using Include="Paramore.Fences.Caching" />
    <Using Include="Paramore.Fences.CircuitBreaker" />
    <Using Include="Paramore.Fences.Fallback" />
    <Using Include="Paramore.Fences.NoOp" />
    <Using Include="Paramore.Fences.RateLimit" />
    <Using Include="Paramore.Fences.Registry" />
    <Using Include="Paramore.Fences.Retry" />
    <Using Include="Paramore.Fences.Timeout" />
    <Using Include="Paramore.Fences.Utilities" />
    <Using Include="Paramore.Fences.Wrap" />
  </ItemGroup>
</Project>
