<Project>
  <PropertyGroup>
    <NoWarn>$(NoWarn);SA1600</NoWarn>
    <IncludeFencesUsings>true</IncludeFencesUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="BenchmarkDotNet.Attributes" />
    <Using Include="BenchmarkDotNet.Configs" />
    <Using Include="BenchmarkDotNet.Jobs" />
    <Using Include="BenchmarkDotNet.Running" />
  </ItemGroup>
</Project>
