#!/usr/bin/env python3
"""Rename the Polly fork to Fences (Phase 2 of fork-migration-plan.md).

Run once, from the repository root, on a clean tree:

    python3 eng/rename-to-fences.py            # do it
    python3 eng/rename-to-fences.py --dry-run  # report only

The commit this produces is mechanical by construction, which is the point: it
should be reviewable by reading this file rather than the diff. Its SHA goes
into .git-blame-ignore-revs so `git blame` still reaches the real author of each
line.

Three things here are load-bearing and easy to get wrong:

1.  ORDERING. The bulk replacement is `Polly` -> `Paramore.Fences`, a *dotted*
    string. Any identifier with `Polly` glued inside it must be rewritten first,
    or `PollyStrongNamePublicKey` becomes `Paramore.FencesStrongNamePublicKey`.
    That is what PASS 1 is for.

2.  CASE SENSITIVITY. Both PASS 2 rules are case-sensitive, and that is what
    makes them independent of each other: `Polly` -> `Paramore.Fences` cannot
    touch lowercase `resilience.polly.*`, so `polly` -> `fences` is free to turn
    it into `resilience.fences.*` (D4). Make either rule case-insensitive and
    the metrics become `resilience.paramore.fences.*`.

3.  URLS ARE PROTECTED. There are ~34 links to `App-vNext/Polly/issues/NNN` in
    code comments, plus `Polly-Contrib/Polly.Contrib.WaitAndRetry`. They cite
    real upstream issues that explain the code they sit next to. Rewriting them
    would break every one. Any http(s) URL is masked before substitution and
    restored afterwards. If a URL *should* change (PackageProjectUrl, the
    pollydocs.org links), that is a deliberate edit in Phase 3 or 7, not a
    side effect here.

Markdown is skipped entirely - see "2b-bis. Why prose is out of scope" in the
plan. Renaming prose mechanically manufactures falsehoods: third-party article
titles, a `Fences-Contrib` organisation that does not exist, a "Fences v7" that
never shipped. Documentation is Phase 7, and it is editorial work.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

# --------------------------------------------------------------------------
# 2a. Path renames. Order matters only in that directories move before the
# .csproj files inside them are renamed; both are done per-entry below.
# --------------------------------------------------------------------------

DIR_RENAMES = [
    ("src/Polly", "src/Paramore.Fences"),
    ("src/Polly.Core", "src/Paramore.Fences.Core"),
    ("src/Polly.Extensions", "src/Paramore.Fences.Extensions"),
    ("src/Polly.RateLimiting", "src/Paramore.Fences.RateLimiting"),
    ("src/Polly.Testing", "src/Paramore.Fences.Testing"),
    ("test/Polly.Core.Tests", "test/Paramore.Fences.Core.Tests"),
    ("test/Polly.Specs", "test/Paramore.Fences.Specs"),
    ("test/Polly.Extensions.Tests", "test/Paramore.Fences.Extensions.Tests"),
    ("test/Polly.RateLimiting.Tests", "test/Paramore.Fences.RateLimiting.Tests"),
    ("test/Polly.Testing.Tests", "test/Paramore.Fences.Testing.Tests"),
    ("test/Polly.TestUtils", "test/Paramore.Fences.TestUtils"),
    ("test/Polly.AotTest", "test/Paramore.Fences.AotTest"),
    ("bench/Polly.Benchmarks", "bench/Paramore.Fences.Benchmarks"),
    ("bench/Polly.Core.Benchmarks", "bench/Paramore.Fences.Core.Benchmarks"),
]

# Repo-level names. These deliberately do NOT take the `Paramore.` prefix: they
# name the repository, not a package, matching Brighter.slnx / Brighter.snk.
#
# The four source files are named after the PASS 1 identifiers they contain, so
# they follow the same replacements rather than the dotted one. Paths here are
# post-DIR_RENAMES.
#
# Deliberately NOT renamed: bench/**/BenchmarkDotNet.Artifacts/**/
# Polly.Core.Benchmarks.*-report-github.md. Those are the recorded results of
# runs that really were against Polly assemblies; renaming the files would
# misattribute the numbers to Fences. They are regenerated by the next
# benchmark run.
FILE_RENAMES = [
    ("Polly.slnx", "Fences.slnx"),
    ("bench/Paramore.Fences.Benchmarks/PollyConfig.cs",
     "bench/Paramore.Fences.Benchmarks/FencesConfig.cs"),
    ("bench/Paramore.Fences.Core.Benchmarks/PollyVersion.cs",
     "bench/Paramore.Fences.Core.Benchmarks/FencesVersion.cs"),
    ("src/Paramore.Fences.Extensions/DependencyInjection/PollyServiceCollectionExtensions.cs",
     "src/Paramore.Fences.Extensions/DependencyInjection/ResilienceServiceCollectionExtensions.cs"),
    ("test/Paramore.Fences.Extensions.Tests/DependencyInjection/PollyServiceCollectionExtensionTests.cs",
     "test/Paramore.Fences.Extensions.Tests/DependencyInjection/ResilienceServiceCollectionExtensionTests.cs"),
]

# Polly.snk is Polly's own 596-byte private key pair. It is deleted, never
# reused; P3.1 generates a fresh Fences.snk.
DELETIONS = ["Polly.snk"]

# --------------------------------------------------------------------------
# 2b. Content replacement.
# --------------------------------------------------------------------------

# PASS 1 - identifiers with `Polly` glued inside them. Must run first.
# `PollyServiceCollectionExtension` is deliberately un-suffixed so that it
# catches both the public type (`...Extensions`, D12) and its test class
# (`...ExtensionTests`).
PASS1 = [
    ("PollyServiceCollectionExtension", "ResilienceServiceCollectionExtension"),
    ("PollyStrongNamePublicKey", "FencesStrongNamePublicKey"),
    ("IncludePollyUsings", "IncludeFencesUsings"),
    ("PollyDiagnosticSource", "FencesDiagnosticSource"),
    ("SKIP_POLLY_ANALYZERS", "SKIP_FENCES_ANALYZERS"),
    ("PollyVersion", "FencesVersion"),
    ("PollyConfig", "FencesConfig"),
    ("EnablePollyMetering", "EnableFencesMetering"),
    ("ListenPollyMetrics", "ListenFencesMetrics"),
]

# PASS 2 - the bulk. Case-sensitive; see note 2 in the module docstring.
PASS2 = [
    ("Polly", "Paramore.Fences"),
    ("polly", "fences"),
]

# PASS 3 - repo-level names, which must NOT carry the `Paramore.` prefix. PASS 2
# has by now turned `Polly.snk` into `Paramore.Fences.snk`; the key file is named
# after the repository, not a package, so it is `Fences.snk` (matching
# Brighter.snk). Runs last, on the output of PASS 2.
PASS3 = [
    ("Paramore.Fences.snk", "Fences.snk"),
    ("Paramore.Fences.slnx", "Fences.slnx"),
]

# Extensions the script will rewrite. Anything not listed is left alone, which
# is why `.md` needs no explicit exclusion and binaries are safe by default.
TEXT_SUFFIXES = {
    ".cs", ".vb", ".fs",
    ".csproj", ".vbproj", ".fsproj", ".props", ".targets", ".slnx",
    ".json", ".yml", ".yaml", ".xml", ".globalconfig", ".editorconfig",
    ".txt", ".dic", ".config", ".ps1", ".bat", ".js", ".sh",
}

# Files with no suffix, or whose suffix is in TEXT_SUFFIXES but which must not
# be touched.
EXCLUDE_PATHS = {
    "LICENSE",
    ".git-blame-ignore-revs",
    "eng/rename-to-fences.py",  # this file talks about both names on purpose
}

EXCLUDE_PREFIXES = (
    "assets/",   # our own brand assets
    "images/",
)

URL_RE = re.compile(r"https?://[^\s\"'`)<>\]]+")

# Third-party package IDs that merely start with `Polly`. They are somebody
# else's published packages and must keep their real names - renaming
# `Polly.Contrib.WaitAndRetry` invents `Paramore.Fences.Contrib.WaitAndRetry`,
# which does not exist on nuget.org and fails restore outright. Masked like a
# URL, and listed longest-first so the longer ID wins.
PROTECTED_RE = re.compile(r"Polly\.Contrib(\.[A-Za-z0-9_]+)*")


def run(*args: str) -> str:
    return subprocess.run(args, check=True, capture_output=True, text=True).stdout


def tracked_files() -> list[str]:
    return [line for line in run("git", "ls-files").splitlines() if line]


def should_rewrite(path: str) -> bool:
    if path in EXCLUDE_PATHS or path.startswith(EXCLUDE_PREFIXES):
        return False
    return Path(path).suffix in TEXT_SUFFIXES


def substitute(text: str) -> str:
    """Apply pass 1 then pass 2, with URLs and third-party IDs masked."""
    urls: list[str] = []

    def mask(match: re.Match[str]) -> str:
        urls.append(match.group(0))
        # \0 cannot occur in any source file we rewrite, so this is unambiguous.
        return f"\0{len(urls) - 1}\0"

    text = URL_RE.sub(mask, text)
    text = PROTECTED_RE.sub(mask, text)

    for old, new in PASS1:
        text = text.replace(old, new)
    for old, new in PASS2:
        text = text.replace(old, new)
    for old, new in PASS3:
        text = text.replace(old, new)

    return re.sub(r"\0(\d+)\0", lambda m: urls[int(m.group(1))], text)


def rename_paths(dry_run: bool) -> None:
    print("== 2a. path renames ==")
    for old, new in DIR_RENAMES:
        if not Path(old).is_dir():
            print(f"   skip (absent): {old}")
            continue
        print(f"   {old} -> {new}")
        if not dry_run:
            run("git", "mv", old, new)
        # The .csproj inside carries the old name too.
        stem = Path(old).name
        proj_old = Path(new) / f"{stem}.csproj"
        proj_new = Path(new) / f"{Path(new).name}.csproj"
        if not dry_run and proj_old.exists():
            run("git", "mv", str(proj_old), str(proj_new))
            print(f"     {proj_old.name} -> {proj_new.name}")

    for old, new in FILE_RENAMES:
        if Path(old).exists():
            print(f"   {old} -> {new}")
            if not dry_run:
                run("git", "mv", old, new)

    for path in DELETIONS:
        if Path(path).exists():
            print(f"   delete {path}  (P3.1 generates a fresh Fences.snk)")
            if not dry_run:
                run("git", "rm", "-q", path)


def rewrite_contents(dry_run: bool) -> int:
    print("\n== 2b. content replacement ==")
    changed = 0
    for path in tracked_files():
        if not should_rewrite(path):
            continue
        p = Path(path)
        try:
            original = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, FileNotFoundError):
            continue
        updated = substitute(original)
        if updated != original:
            changed += 1
            if not dry_run:
                p.write_text(updated, encoding="utf-8")
    print(f"   {changed} files rewritten")
    return changed


MANGLED_RE = re.compile(r"Paramore\.Fences[A-Za-z]")


def guard() -> bool:
    """After the passes, `Paramore.Fences` must never be glued to a letter.

    Any hit is a PASS 1 case that was missed - the dotted replacement landed
    inside an identifier and produced something like
    `Paramore.FencesStrongNamePublicKey`.

    Scoped to the files this script actually rewrites. A repo-wide `git grep`
    reports this script and the migration plan, both of which spell the failure
    mode out in prose on purpose.
    """
    print("\n== guard ==")
    hits: list[str] = []
    for path in tracked_files():
        if not should_rewrite(path):
            continue
        try:
            text = Path(path).read_text(encoding="utf-8")
        except (UnicodeDecodeError, FileNotFoundError):
            continue
        for n, line in enumerate(text.splitlines(), start=1):
            if MANGLED_RE.search(line):
                hits.append(f"{path}:{n}:{line.strip()}")
    if hits:
        print(f"   FAIL - {len(hits)} identifier(s) mangled by the dotted replacement:")
        for line in hits[:20]:
            print(f"     {line}")
        if len(hits) > 20:
            print(f"     ... and {len(hits) - 20} more")
        print("\n   Add the offending identifier to PASS1 and re-run from a clean tree.")
        return False
    print("   OK - no mangled identifiers")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="report what would change without touching anything")
    args = parser.parse_args()

    if not Path(".git").is_dir():
        print("Run this from the repository root.", file=sys.stderr)
        return 2

    if not args.dry_run and run("git", "status", "--porcelain").strip():
        print("Working tree is not clean. This script rewrites hundreds of files; "
              "commit or stash first so it can be undone with a single reset.",
              file=sys.stderr)
        return 2

    rename_paths(args.dry_run)
    rewrite_contents(args.dry_run)

    if args.dry_run:
        print("\n(dry run - nothing written, guard not run)")
        return 0

    return 0 if guard() else 1


if __name__ == "__main__":
    sys.exit(main())
